### ISSUE TITLE
DOCUMENTATION -  ADDING CONTRIBUTING FILE , IMPROVE IT 

### ISSUE THREAD

**Issue by akrish4** [sharmaumang001/Mobile-Brower#1]
Hi @sharmaumang001 

I found there is no CONTRIBUTING file in this repository 
I would be glad to work on it 

Kindly do assign me 

I can add a great contributing file with all contributing guidlines in it 
Kindly do add the DWOC  and Level label

**Comment by sharmaumang001** [comment]
Please add all the documentation 
Update Readme 
Contributing File 
Any other if you want to comment and add

**Comment by akrish4** [comment]
Yes I will add contributing file and Update readme file in this particular issue

**Comment by sharmaumang001** [comment]
Add screenshots of the app (you may get them from the play store)
Add libraries used, open-source programs, and contributors.
You can take help from( [https://github.com/thinktocode/COVID-19-Tracker](https://github.com/thinktocode/COVID-19-Tracker))

**Comment by sharmaumang001** [comment]
Hey ,

Are you working?

**Comment by akrish4** [comment]
yes , I will open the pr  soon 
I was a bit busy , 
Let me know is there any issues ?

**Comment by akrish4** [comment]
can you share the link of this app in playstore to get screenshots 
@sharmaumang001

**Comment by sharmaumang001** [comment]
Check out readme.

**Comment by akrish4** [comment]
yeah got it @sharmaumang001

**Comment by akrish4** [comment]
shall i add a new folder so that i can add all screenshots in it , shall i name it as media?
@sharmaumang001

**Comment by sharmaumang001** [comment]
Try taking help from the repo i provided above, do the way its done there.

**Comment by akrish4** [comment]
okay fine
