### ISSUE TITLE
ADD CONTRIBUTORS.md FILE  

### ISSUE THREAD

**Issue by akrish4** [sharmaumang001/Mobile-Brower#19]
Hi @sharmaumang001 
As we know this is a open source repository and there maany contrbutors right now to this project and will be increasing in future and hence I would like to add a contributors.md file which will contain all the contributors deatils like their profile picture and their full name in a tabular format 
Kindly do assign me

**Comment by sharmaumang001** [comment]
Hey!
Already asked you to do so in issue#1
All the best
