### ISSUE TITLE
INTEGRATE WELCOME AND GREETING BOT 

### ISSUE THREAD

**Issue by akrish4** [sharmaumang001/Mobile-Brower#2]
Hi  @sharmaumang001 

I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
( config file having a proper message)

**Kindly do assign me this issue**

For reference, kindly check out: https://github.com/apps/welcome

Kindly do add the DWOC and Level label too

**Comment by sharmaumang001** [comment]
I have assigned this to you 
You can add and create PR

**Comment by akrish4** [comment]
This is a feature update , 
doesn't it deserve a better level

**Comment by sharmaumang001** [comment]
Does it matter?
Moreover, I think It is an enhancement for the repo not a feature update to the application.

**Comment by akrish4** [comment]
yes it is enhancement for the repo

**Comment by sharmaumang001** [comment]
You still doing it?

**Comment by akrish4** [comment]
yes , I will open the pr in 1 hr, I was bit busy , Let me know any issue ?

**Comment by sharmaumang001** [comment]
No issues just asking

**Comment by akrish4** [comment]
@sharmaumang001 
Now you just have to install and configure the bot using the official github app https://github.com/apps/welcome and rest bot will do since I have added the config.yml file
Theses bot are made by github only
