### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [sharmaumang001/Mobile-Brower#24]
**Is your feature request related to a problem? Please describe.**
Welcome is a bot that encourages first-time contributors to get started with contributing to your repo. It adds a professional and welcoming look to your repository and would encourage new users who are trying to get started with the project
**Describe the solution you'd like**
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome
**Describe alternatives you've considered**
I have considered adding Welcome Bot
**Additional context**
![Bot6](https://user-images.githubusercontent.com/64524822/104833823-a845a100-58c1-11eb-8d74-e197b8ce8ee3.png)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by sharmaumang001** [comment]
Duplicate issue #2
