### ISSUE TITLE
ADD CODE OF CONDUCT FILE 

### ISSUE THREAD

**Issue by akrish4** [sharmaumang001/Mobile-Brower#3]
Hi @sharmaumang001 

There is no code of conduct file in this repository 
code of conduct is a file that will be required to a open source project  for the contributors to follow the guidleines 

Kindly let me know if you can assign me this issue

**Comment by sharmaumang001** [comment]
Add code of conduct and also add it to README.

**Comment by akrish4** [comment]
yes sure

**Comment by akrish4** [comment]
#16  PR
