### ISSUE TITLE
Readme updation by including various open-source programs this project is a part of and also gifs will make it look better

### ISSUE THREAD

**Issue by Sloth-Panda** [sharmaumang001/Mobile-Brower#8]
let me know i can help with this

**Comment by sharmaumang001** [comment]
Same issues already there,
With the name Update README
Once it gets solved, and if there still will be a need for an update I will assign you this one

**Comment by Sloth-Panda** [comment]
Yes, I saw that issue being raised I included this for as in no issues it was mentioned to add open-source programs and gifs stuffs so

**Comment by Sloth-Panda** [comment]
Thanks for assigning can you please remove  the duplicate tag and add dwoc and level tags

**Comment by Sloth-Panda** [comment]
pr -> #22
